### ISSUE TITLE
Setup of Kanbab board - Final Group Capstone

### ISSUE THREAD

**Issue by ForHemer** [mateo951/Final-Capstone-backend#18]
Hello reviewer,

We are a team of  3 members :
- [ ] @ForHemer 
- [ ] @mateo951 
- [ ] @blessedjasonmwanza 

Kindly help us review our [kanban board](https://github.com/mateo951/Final-Capstone-backend/projects/1).

![Screenshot from 2022-07-18 13-35-39](https://user-images.githubusercontent.com/88809610/179571360-29e12d30-24a1-469b-bc4f-3e59e90f5007.png)

**Comment by MuriloRoque** [comment]
Hi @ForHemer, @blessedjasonmwanza, @mateo951,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
